FROM neos/centos:centos7

# PostgreSQL image for NEOS
# Volumes:
#  * /var/lib/psql/data   - Database cluster for PostgreSQL
# Environment:
#  * $POSTGRESQL_USER     - Database user name
#  * $POSTGRESQL_PASSWORD - User's password
#  * $POSTGRESQL_DATABASE - Name of the database to create
#  * $POSTGRESQL_ADMIN_PASSWORD (Optional) - Password for the 'postgres'
#                           PostgreSQL administrative account

MAINTAINER Neos By Bold <suporte@neosbybold.com>

ENV POSTGRESQL_VERSION=9.4 \
    HOME=/var/lib/pgsql \
    PGUSER=postgres

EXPOSE 5432

# This image must forever use UID 26 for postgres user so our volumes are
# safe in the future. This should *never* change, the last test is there
# to make sure of that.
RUN yum install -y centos-release-scl epel-release && \
    yum -y --setopt=tsflags=nodocs install gettext bind-utils rh-postgresql94 nss_wrapper && \
    yum clean all && \
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    mkdir -p /var/lib/pgsql/data && \
    test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)"

#COPY run-*.sh /usr/local/bin/ \
#     container-entrypoint /usr/local/bin/ \
#     common.sh /usr/share/container-scripts/postgresql \
#     scl_enable /usr/share/container-scripts/postgresql \
#     postgres.conf.template /usr/share/container-scripts/postgresql \
#     recovery.conf.template /usr/share/container-scripts/postgresql \
#     passwd.template /usr/share/container-scripts/postgresql \
#     fix-permissions /usr/libexec/fix-permissions

# Loosen permission bits to avoid problems running container with arbitrary UID
ADD root /
RUN /usr/libexec/fix-permissions /var/lib/pgsql \
    && /usr/libexec/fix-permissions /var/run/postgresql \
    && chmod +x /usr/bin/run-postgresql* \
    /usr/share/container-scripts/postgresql/common.sh \
    /usr/bin/container-entrypoint 

# Get prefix path and path to scripts rather than hard-code them in scripts
ENV CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/postgresql \
    ENABLED_COLLECTIONS=rh-postgresql94

# When bash is started non-interactively, to run a shell script, for example it
# looks for this variable and source the content of this file. This will enable
# the SCL for all scripts without need to do 'scl enable'.
ENV BASH_ENV=${CONTAINER_SCRIPTS_PATH}/scl_enable \
    ENV=${CONTAINER_SCRIPTS_PATH}/scl_enable \
    PROMPT_COMMAND=". ${CONTAINER_SCRIPTS_PATH}/scl_enable"

VOLUME ["/var/lib/pgsql/data"]

USER 26

ENTRYPOINT ["container-entrypoint"]
CMD ["run-postgresql"]